#+TITLE: Baking
#+OPTIONS: \n:t

* Baking
** Focaccia Bread :Bread:
This [[https://www.youtube.com/watch?v=HTD-z1wd0tw&t=0s][video]] seemed like an easy way to make this bread

Dough Ingredients:
- 9 g Instant Yeast
- 335 g Water (105-115 F)
- 450 g Flour (Bread or All purpose)
- 9 g Salt
- 9 g Extra Virgin Olive Oil

For Baking:
- 20 g Extra Virgin Olive Oil
- 20 g Water

Topping Ideas:
- Coarse Kosher Salt
- Fresh Rosemary
- Garlic
- Chiles

** Flour Tortillas :Bread:Mexican:
The only struggled is with making them round this [[https://youtu.be/j0gjlSgO7VU?t=64][video]] helps with how you should roll them.
This is the [[https://thecafesucrefarine.com/best-ever-homemade-flour-tortillas/][recipe]] I followed when I was making them.
Making them round is really hard a [[https://www.amazon.com/Victoria-TOR-003-FBA_TOR-003-Tortilla-Press/dp/B00HWEIKZO][tortilla press]] could help with this.
|--------+---------------+----------+---------------+------------------------+------------|
| Amount | Platent bloem | Zout     | Baking powder | Extra virgin olive oil | Warm water |
|--------+---------------+----------+---------------+------------------------+------------|
|     16 | 375g          | 5g       | 5g            | 80ml                   | 240ml      |
|      1 | 23.4375 g     | 0.3125 g | 0.3125 g      | 5 ml                   | 15 ml      |
|     22 | 515.625 g     | 6.875 g  | 6.875 g       | 110 ml                 | 330 ml     |
|--------+---------------+----------+---------------+------------------------+------------|
#+TBLFM: @3=@-1/@2$1::@4$2..@4$6=@-1*$1
** Flatbread
[[https://www.recipetineats.com/easy-soft-flatbread-yeast/][Link]]

Ingredients:
- 300 g plain flour (all purpose flour) (level cups, unsifted, not packed), + keep 1/4 cup extra for dusting & adjusting dough
- 1/2 tsp salt
- 3 1/2 tbsp / 50g unsalted butter (1.75 oz)
- 185 ml milk
- 1/2 tbsp oil (for cooking)

Steps:
1) Melt butter in milk: Combine butter and milk and heat until butter is just melted – on stove or in microwave.
2) Combine Dry: Combine 2 cups flour, salt, butter and milk in a bowl.
3) Knead 2 minutes: Sprinkle work surface with flour then knead for a few minutes until it is smooth – it doesn't need much kneading. Add extra flour if the dough is too sticky.
4) Rest 30 minutes: Wrap with cling wrap and rest at room temperature for 30 minutes or so.
5) Roll into rounds: Dust bench top with flour, cut dough into 4 pieces, roll into balls, then roll out into about 1/8" / 0.3cm thick rounds.
6) Heat oil: Heat 1/2 tbsp olive oil in a non stick pan over medium heat – or lower if you have a heavy based skillet. (Note 1)
7) Cook: Place one flatbread in the pan, cook for around 1- 1 1/2 minutes – it should bubble up (see photo in post)- then flip and cook the other side, pressing down if it puffs up. There should be a smallish golden brown spots on both sides.
8) Keep wrapped in tea towel: Stack the cooked bread and keep wrapped with a tea towel – the moisture helps soften the surface, making them even more pliable. Continue to cook with remaining pieces.
9) Brush with butter or oil (optional): Brush or spray bread with olive oil or melted butter, for a more luxurious finish. Or even with melted butter mixed with minced garlic for a garlic butter version!
** Cheesy Garlic Bread
[2 pieces of 22cmx17cm (serves 2-4 people)]
✤ Dough
  - 200g Bread flour
  - 5g(0.5tbsp) Instant dry yeast
  - 8g(1tbsp) Sugar
  - 4g(0.5tbsp) Salt
  - 15g(2tbsp) Olive oil (Cooking oil can be used)
  - 120ml Warm water

✤ Cream Cheese Sauce
  - 10g(0.5tbsp) Minced garlic
  - 20g(2tbsp) Melted unsalted butter
  - 30g(1big tbsp) cream cheese

✤ Toppings
  - 280g Mozzarella cheese
  - Parmesan Cheese
  - Oregano (can be omitted) Parsley can be used

✤ Dipping sauce
  - Honey
  - Tomato Sauce

1. Combine warm water with sugar and dry yeast.
2. Add flour and salt and start kneading.
3. Knead dough until it forms a nice not so sticky dough ball.
4. Add olive oil to the dough and knead it into the dough.
5. Let rest until it doubles/triples in size (around 1 hour in a warm environment).
6. Start preheating the oven at 210℃.
7. Create cream cheese sauce by combining everything in the cream cheese sauce list.
8. Split the dough into 2 and roll the dough into a thin piece.
9. Top with cream cheese mixture and mozzarella.
10. Place into the oven for 8 - 10 minutes.

[[https://www.youtube.com/watch?v=8LPVOjjSgDE][Link]]
** Onion bread
1. use the same dough recipe as [[*Cheesy Garlic Bread][Cheesy Garlic Bread]].
2. Preheat the oven at 210℃.
3. Then top it with yellow onion and grated cheese.
4. Bake in the oven for 8 - 10 minutes at 210℃.
