#+TITLE: Cooking
#+DESCRIPTION: This is my cooking guide here I place recipes I have found that look interesting and those I've tried. I also make templates for certain styles of food to allow for more creativity.
#+AUTHOR: Tobin Stultiens
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: tags:nil

* Recipes
** Chicken Enchiladas :Chicken:Mexican:
- 600 - 700 gram chicken
- 1 onion, chopped
- creme fraiche
- 1 cup shredded cheese
- 1 tablespoon dried parsley
- 1/2 teaspoon dried oregano
- 1/2 teaspoon ground black pepper
- 1/2 teaspoon salt (Optional)
- 1 (15 ounce) can tomato sauce
- 1/2 cup water
- 1 tablespoon chili powder
- 1/3 cup chopped green bell pepper
- 1 clove garlic, minced
- 8 (10 inch) flour tortillas
- 1 (12 ounce) jar taco sauce
- 3/4 cup shredded cheese
Maybe watch out with the chili powder on this one.

1. Preheat oven to 350 degrees F (175 degrees C).
2. In a medium, non-stick skillet over medium heat, cook chicken until no longer pink and juices run clear. Drain excess fat. Cube the chicken and return it to the skillet. Add the onion, sour cream, Cheddar cheese, parsley, oregano and ground black pepper. Heat until cheese melts. Stir in salt, tomato sauce, water, chili powder, green pepper and garlic.
3. Roll even amounts of the mixture in the tortillas. Arrange in a 9x13 inch baking dish. Cover with taco sauce and 3/4 cup Cheddar cheese. Bake uncovered in the preheated oven 20 minutes. Cool 10 minutes before serving.

** Korean Fried Chicken :Chicken:Korean:Frying:
- 2 pounds boneless skinless chicken thighs, cut into 1 inch pieces
- 1/4 cup flour
- 2 eggs
- 1/2 cup cornstarch
- oil for frying
- 1/3 cup Korean gojuchang red pepper paste
- 3 tablespoons rice vinegar
- 1/4 cup brown sugar
- 2 tablespoons soy sauce
- 1 teaspoon sesame seeds for garnish

- Toss the chicken in the flour, then dredge into the egg and finally coat in the cornstarch.
- In a large glass bowl add the gojuchang, vinegar, brown sugar and soy sauce and whisk until well combined.
- Heat up a heavy bottomed pan with 3 inches of oil to 375 degrees.
- Fry the chicken for 3-4 minutes or until browned and crispy.
- Drain the fried chicken and add to the bowl with the sauce.
- Toss to combine, garnish with sesame seeds and serve immediately.

** Spicy Sesame Rice Bowl :Rice_Bowl:Beef:
[[https://www.goodhousekeeping.com/food-recipes/a42379/spicy-sesame-rice-bowls-recipe/][Link]]\\
Ingredients:
- 1/3 c. Korean red pepper paste (gochujang)
- 2 tbsp. toasted sesame oil
- 1 tbsp. soy sauce
- 1 tbsp. sugar
- 3 cloves garlic, crushed with press
- 1 lb. beef top round, cut against grain into very thin 2"-long slices
- 12 oz. medium shiitake mushrooms, stemmed
- 1 seedless (English) cucumber, thinly sliced
- 1/4 c. rice vinegar
- 5 oz. baby spinach
- 6 c. cooked white rice, hot
- Thinly sliced green onions, shredded carrots, kimchi and sesame seeds for serving

Directions:
1. In large bowl, whisk red pepper paste, sesame oil, soy sauce, sugar, garlic and 1/4 cup of water until smooth; set aside 1/2 cup of sauce. To bowl with remaining sauce, add beef and pinch salt, tossing to coat. Let stand at least 10 minutes or refrigerate up to overnight.
2. Add beef to pressure-cooker pot along with mushrooms. Cover, lock and bring up to pressure on high. Reduce heat to medium-low, maintaining pressure. Cook 10 minutes.
3. While beef cooks, toss cucumber with vinegar and 1/4 teaspoon of salt; set aside.
4. Release pressure by using quick-release function. Divide spinach among 6 serving bowls; top each with 1 cup of rice. Drain cucumbers. Top rice with beef, mushrooms, cucumbers, green onions, carrots, kimchi and sesame seeds; drizzle with reserved sauce.
Comments:\\
Korean red pepper paste is te vervangen met sambal oelek al moet het met maizena verdikt worden. \\
Kogelbiefstuk is hiervoor aan te raden.

** Sesame Beef :Beef:Wok:
[[https://www.allrecipes.com/recipe/14679/sesame-beef/][Link]]
Ingredients: 
- 1 pound round steak 
- 4 tablespoons soy sauce 
- 4 tablespoons white sugar 
- 4 tablespoons vegetable oil 
- 2 cloves garlic, minced 
- 2 green onions, chopped 
- 2 tablespoons sesame seeds 
 
Directions: 
 
1. Mix soy sauce, sugar, oil, garlic, and onions in a large bowl. Set aside. 
2. Cut steak into strips and add to bowl. Cover and refrigerate overnight, or at least 30 minutes. 
3. Cook in wok or frying pan until brown, about 5 minutes. Add sesame seeds and cook for additional 2 minutes. 

** Easy Mexican Casserole :Mexican:Beef:
[[https://www.allrecipes.com/recipe/20680/easy-mexican-casserole/][Link]]
 
- 1 pound lean ground beef 
- 2 cups salsa 
- 1 (16 ounce) can chili beans, drained 
- 3 cups tortilla chips, crushed 
- 2 cups sour cream 
- 1 (2 ounce) can sliced black olives, drained 
- 1/2 cup chopped green onion 
- 1/2 cup chopped fresh tomato 
- 2 cups shredded Cheddar cheese 
 
1. Preheat oven to 350 degrees F (175 degrees C). 
2. In  a large skillet over medium-high heat, cook ground beef until no longer  pink. Stir in salsa, reduce heat, and simmer 20 minutes, or until  liquid is absorbed. Stir in beans, and heat through. 
3. Spray  a 9x13 baking dish with cooking spray. Spread crushed tortilla chips in  dish, and then spoon beef mixture over chips. Spread sour cream over  beef, and sprinkle olives, green onion, and tomato over the sour cream.  Top with Cheddar cheese. 
4. Bake in preheated oven for 30 minutes, or until hot and bubbly. 

** Black pepper beef :Beef:Wok:
[[https://schoolofwok.co.uk/tips-and-recipes/black-pepper-beef][Link]]\\
Ingredients:
- 350g steak, sliced into strips against the grain
- 1 onion, julienned
- 1/2 red pepper, julienned
- 1 spring onion
- 1/4 of a thumb size piece of ginger

THE MARINADE
- 1 teaspoon cornflour (cornstarch)
- 1 teaspoon light soy sauce
- 1 teaspoon pure sesame oil

THE SAUCE
- 1/4 teaspoon salt
- 1/2 teaspoon sugar
- 1/2 teaspoon crushed black pepper
- 1 tablespoon Lee Kum Kee black pepper sauce
- 50 ml chicken stock
- 1 tablespoon light soy sauce
- 1 tablespoon oyster sauce
- 2 teaspoons Shaoxing rice wine

Preparation:
1. Remove any rind or fat from the steak, then slice thinly. Tenderize by bashing them with a cleaver or meat hammer, creating a large surface area for quick cooking.
2. Mix all the marinade ingredients with the meat. Massage the marinade into the meat, marinade for 30 minutes, or overnight for more flavor.
3. Mix the sauce ingredients together in a small bowl.
Cooking:
1. Heat 2 tablespoons vegetable oil in a wok to high heat. Sear your meat for a couple of minutes on each side and set aside.
2. Add oil to the wok and when smoking hot, add the ginger and spring onions, once they have slightly softened, add the pepper and onions.
3. Maintaining the high heat, pour in your sauce, return the meat to the wok and continue to stir-fry for an additional 30 seconds.
4. Serve and enjoy.

** Wraps :Lunch:Snacks:
*** Kipfilet variant 
- kipfilet (of gerookte kipfilet) 
- paar plakjes komkommer 
- halve bosui 
- snufje peper 

*** Groenten wrap 
- 1/4 rode paprika 
- handje rucola 
- halve bosui 
- snufje peper 
- snufje chilipoeder 
 
*** Wrap met kip, sla en komkommer 
- 1 tl roomkaas met kruiden 
- handje ijsbergsla/eikenblad melange 
- plakje kipfilet (of gerookte kip)
- paar plakjes komkommer 
- snufje peper 

** Stokbrood met pittig gehakt :Bread:Beef:
[[https://www.lekkerensimpel.com/pittig-stokbrood-met-gehakt/][Link]]

** Sweet and sour chicken :Chicken:Chinese:Frying:
[[https://www.youtube.com/watch?v=RUDPussbU04][Link]]

Ingredients:\\

For marination:
- Salt- 1/2 tsp
- Pepper powder- 1/2 tsp

For the Batter:
- Maida/All Purpose Flour- 3 tbsp measure
- Cornflour- 2 tsp measure
- Baking powder- 1/4 tsp
- Salt- 1/4 tsp
- Egg white- of 1 egg
- Chilled Water- 4 tbsp

Sweet & Sour Sauce:
- Tomato Ketchup- 4 tbsp
- Sugar- 3 tbsp
- White Vinegar- 3 tbsp
- Dark Soy Sauce- 3/4 tsp

Other Ingredients:
- Green bell peppers/capsicum, cubed- 1 cup (around 70 gms)
- Red bell peppers/capsicum, cubed- 1 cup ( around 70 gms)
- Oil- 1/2 tbsp oil + oil for deep frying the chicken

Preparation:
1. Wash and leave the chicken pieces/fillets to drain.
2. Pat dry if required and cut them into bite sized pieces. You could use a mix of boneless dark and white meat, makes the chicken pieces moist and juicy.
3. Marinate with salt and pepper powder and set aside for 20 mins.
4. Add all the ingredients of the sweet and sour sauce in a small bowl and give a mix. Set aside for use later.
5. Prepare the batter/mix as per ingredients specified above.

Process:
1. Heat oil for deep frying in a skillet or wok or kadai.
2. Once the oil is medium hot, dip the marinated chicken pieces in the batter and drop them in oil side by side to not crowd the pan.
3. Fry the chicken pieces on medium heat for 1 minute without turning them.
4. After that keep turning & frying the pieces for another 4-5 mins till golden in colour. Take it out & repeat the same with the next batch.
5. Now take a wok or kadai and add 1/2 tbsp oil.
6. Keep it on high heat and add the cubed peppers. Stir fry on high heat for 1 minute and then add the sweet & sour sauce. Mix and continue to fry on high heat for another minute till the sauce is cooked and thick.
7. Now add the fried chicken pieces, give a mix and continue to stir fry to coat the chicken pieces well with the sauce. This should take around 2 mins.
8. Serve with noodles or fried rice.

** Spicy Thai Basil chicken :Chicken:Thai:
[[https://foodwishes.blogspot.com/2017/04/spicy-thai-basil-chicken-my-pad-krapow.html][Link]] 
 
Ingredients: 
- 1 pound freshly chopped chicken thighs 
- 1/4 cup sliced shallots 
- 4 cloves garlic, minced 
- 2 tablespoons minced Thai chilies, Serrano, or other hot pepper 
- 1/3 cup chicken broth 
- 1 tablespoon soy sauce, or as needed 
- 1 tablespoon oyster sauce 
- 2 teaspoons fish sauce 
- 1 teaspoon white sugar 
- 1 teaspoon brown sugar 
- 1 bunch basil leaves, sliced very thin with a sharp knife (about a cup once sliced) 

* Templates
** Stir Fry :Template:Wok:
This is a stir fry template here I describe the required parts of a stir fry and the optional parts.

Required:
- Garlic
- Ginger

Optional:
Vegetable:
- Mushrooms
- Onion
- Red pepper
- Spring onion
- Peppers

Meat:
- Chicken
- Pork
- Beef

Sauces:
- Teriyaki Sauce
- Soy based sauce

** Burritos :Beef:Template:Mexican:
ESSENTIAL INGREDIENTS 
- Rundergehakt 700-800 gram 
- Mais 
- Paprika 
- Onions 
- Wrap 
- Cheese 
- Creme fraiche 
 
POSSIBLE INGREDIENTS 
- Chili Pepers 
- Knoflook 
- Tomaat 
- Champignons 
- Sla 
 
Spices: 
- Taco

** Quesedillas :Vegan:Mexican:Cheese:
Ingredients: 
- Wraps 
- Cheese 
- Olive oil or Butter
 
Optional: 
- Bacon stukjes 
- Avocado 
- Sla 
- Lente uien 
- Tomatoes Diced 
- Prosciutto  
- Thinly sliced chorizo

** How to pimp my noodles :Noodles:
This is a simple guide on how to pimp your instant [[https://www.budgetbytes.com/6-ways-to-upgrade-instant-ramen/][noodles]].

Ingredients:
- Vegetables
- 1 clove Garlic
- 1/2 tsp grated ginger
- 250 ml broth
- 250 ml water
- 1 package instant ramen
- 1 egg
- 1 green onion

Steps:
1. Add the oil, garlic, and ginger to a small sauce pot and sauté over medium for about one minute.
2. Add your vegetable of choice and saute for about a minute.
3. Add the broth and water, and bring to a boil.
4. Now make your broth your own add sauces to the broth and taste whether this is what you like. My personal favorite thing to add is sriracha and chicken bouillon as broth.
5. Crack the egg into the broth for about a minute, then add your instant noodles for 3 minutes.
6. Transfer the soup to a bowl, then top it with sliced green onion.

** Rice :Rice:
This is the formule for how to make rice.
The only requirement is that you wash your rice before following this.
|---------------+---------|
| Rijst         | Water   |
|---------------+---------|
| Sushi Rijst   | 1 + 1/3 |
|---------------+---------|
| Normale Rijst | 1 + 1/2 |
|---------------+---------|

* Sauces
** Salsa :Mexican:Sauce:
Got the recipe from this [[https://www.youtube.com/watch?v=Upqp21Dm5vg][video]].

- 2-3 large, ripe tomatoes - firm, fragrant, preferably on the vine
- 1 medium red onion
- 1 Jalapeño or a small piece of habanero
- Fresh garlic (1 clove)
- salt to taste
- Freshly ground pepper to taste
- Scallions, aka green onions (one)
- parsley (optional)
- 1 red bell pepper (optional)
- 1 mango (optional) - soft but not mushy to the touch

** Teriyaki Sauce :Sauce:Japanese:
*** 3 Ingredient Version
Basic teriyaki sauce

Ingredients: 
- 1/3 cup Japanese mirin (sweet rice wine) 
- 2 tablespoons soy sauce, low sodium preferred 
- 1 tablespoon sugar 

Instructions:
1. Combine all the ingredients of the Teriyaki Sauce in a sauce pan. On low heat, simmer and reduce it to a thicker consistency, about 10 minutes.

[[https://www.tasteandtellblog.com/teriyaki-chicken/][Another way to make teriyaki sauce]]
[[https://www.bbcgoodfood.com/recipes/teriyaki-sauce][Fridge sauce]]

*** Improved version
Basic teriyaki sauce

Ingredients: 
- 1/3 cup Japanese mirin (sweet rice wine) 
- 2 tablespoons soy sauce, low sodium preferred 
- 1 tablespoon sugar 
- 1-2 tablespoons honey
- 1 cloves garlic

Instructions:
1. Combine all the ingredients of the Teriyaki Sauce in a sauce pan. On low heat, simmer and reduce it to a thicker consistency, about 10 minutes.

[[https://www.tasteandtellblog.com/teriyaki-chicken/][Another way to make teriyaki sauce]]

*** Storing version
Ingredients: 
- 1-2 tablespoons honey
- 1 cloves garlic
- 4cm piece ginger
- 60 g light brown soft sugar
- 50ml soy sauce
- 1 tbsp cornflour
- 1 tbsp rice wine vinegar

[[https://www.bbcgoodfood.com/recipes/teriyaki-sauce][Fridge sauce]]
** Garlic sauce :Sauce:
For the love of god don't put any lemon in it
Jesus fucking christ that's awful
[[https://fussfreeflavours.com/easy-kebab-shop-garlic-sauce-recipe/][Link]]


| Amount | Ingredient   |
|--------+--------------|
| 2 tbsp | mayonnaise   |
| 2 tbsp | yoghurt      |
| 1      | clove garlic |
|--------+--------------|

1. Boil a kettle of water. Slice the garlic thinly, and transfer to a sieve. Pour the kettle of boiled water over the garlic
2. With the back of a knife, crush the garlic with a pinch of salt into a paste.
3. Mix garlic, mayonnaise and yoghurt. Season to taste with salt and pepper.
** Cheese dip :Cheese:Dip:
[[https://www.youtube.com/watch?v=PTbdvND_YLQ][Sodium Citrate]]
This looks like a better way to make a dip.
* Baking
** Focaccia Bread :Bread:
This [[https://www.youtube.com/watch?v=HTD-z1wd0tw&t=0s][video]] seemed like an easy way to make this bread

** Flour Tortillas :Bread:Mexican:
The only struggled is with making them round this [[https://youtu.be/j0gjlSgO7VU?t=64][video]] helps with how you should roll them.
This is the [[https://thecafesucrefarine.com/best-ever-homemade-flour-tortillas/][recipe]] I followed when I was making them.
Making them round is really hard a [[https://www.amazon.com/Victoria-TOR-003-FBA_TOR-003-Tortilla-Press/dp/B00HWEIKZO][tortilla press]] could help with this.
|--------+---------------+----------+---------------+------------------------+------------|
| Amount | Platent bloem | Zout     | Baking powder | Extra virgin olive oil | Warm water |
|--------+---------------+----------+---------------+------------------------+------------|
|     16 | 375g          | 5g       | 5g            | 80ml                   | 240ml      |
|      1 | 23.4375 g     | 0.3125 g | 0.3125 g      | 5 ml                   | 15 ml      |
|     22 | 515.625 g     | 6.875 g  | 6.875 g       | 110 ml                 | 330 ml     |
|--------+---------------+----------+---------------+------------------------+------------|
#+TBLFM: @3=@-1/@2$1::@4$2..@4$6=@-1*$1
* Soup
** Miso Soup :Soup:Japanese:
This [[https://minimalistbaker.com/15-minute-miso-soup-with-greens-and-tofu/][recipe]] was alright although quite fishy might need some adjustments.

* Ideas
** Focaccia Sandwich and Pizza :Bread:Pizza:Sandwich:
This [[https://www.youtube.com/watch?v=eq8vuOSnV68][video]] seemed interesting about how they make use of focaccia

** zha jiang min :Chinese:Noodles:Pork:
[[https://youtu.be/NM4ArR-qbHQ][Link]] \\
1-Hour Noodles \\
Servings: 2 \\
\\ 
Ingredients 
- 2 tablespoons plus 1 teaspoon vegetable oil, divided 
- 1 tablespoon plus 1 teaspoon minced garlic, divided 
- 1 tablespoon minced fresh ginger 
- 1 tablespoon minced shallot 
- 4 ounces 80/20 ground pork 
- 1 tablespoon fermented soy bean paste 
- 1 tablespoon sweet bean sauce 
- 1 teaspoon dark soy sauce 
- ¼ cup cornstarch slurry (8 teaspoons cornstarch mixed with 4 teaspoons water) 
- 1 large egg, beaten 
- 360 grams fresh noodle of choice 
- 1 Persian cucumber, thinly sliced 
- ½ cup fresh cilantro leaves 
 
Preparation 
1. In  a medium pan, heat 1 tablespoon of vegetable oil over medium heat. Add 1  tablespoon of minced garlic, the ginger, and shallot and sauté until  lightly aromatic, 1-2 minutes. Add the ground pork to the pan and cook,  undisturbed, until golden brown, 3-5 minutes.  
2. Meanwhile,  in a small pan, heat another tablespoon of vegetable oil over  medium-low heat. Add the soy bean paste and sweet bean sauce and cook  until caramelized, 1-2 minutes, being careful not to burn. 
3. Add  the caramelized bean paste mixture to the ground pork mixture and stir  to combine. Add the soy sauce and cook for another 30 seconds to  incorporate. Add the cornstarch slurry, reduce the heat to low, and  simmer for about 15 minutes, adding a few tablespoons of water at a time  as needed to keep the mixture at a simmer. 
4. Meanwhile,  heat a small pan over low heat. Add the remaining  teaspoon of  vegetable oil, then pour in the egg and tilt the pan to spread in a thin  layer. Cook until the top is just set, then remove the egg crepe from  the pan. Let cool, then thinly slice. 
5. Cook the noodles according to the package instructions, then drain.  
6. Place  the cooked noodles in a serving bowl and top with the ground pork  mixture. Garnish with the egg crepe strips, cucumber, cilantro, and  remaining teaspoon of minced garlic. 
Enjoy! 
** Calzone :Italian:Pizza:
[[https://www.youtube.com/watch?v=PrbpuNZyoUQ][link]]
** Poblano con queso taco :Mexican:Cheese:Taco:
This [[https://youtu.be/YtkyC2Ctz6E][recipe]] looked interesting.
** Crispy Baked wings :Chicken:Wings:
This just looks [[https://www.youtube.com/watch?v=mh2AXh1eRmE][good]].
** PK Chicken Karahi :Chicken:
[[https://www.youtube.com/watch?v=4PMmH2-5wJM][link]]

* Fermenting
** Pickled Onions :Pickled:
This is a nice acidic [[https://www.youtube.com/watch?v=K4HbmPu_M_4&t=24s][recipe]].
