#+TITLE: Soup
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: \n:t

* Soup
** Miso Soup :Soup:Japanese:
This [[https://minimalistbaker.com/15-minute-miso-soup-with-greens-and-tofu/][recipe]] was alright although quite fishy might need some adjustments.
** Asperge Soup :Soup:
Voor 5l asperges soep
ingredienten:
- 250 boter
- 3 dikke uien
- 6 grote eetlepels meel en een ½ liter melk
- 5 maggie blokken
- 4 eieren
- 3kg asperges (mag stukken zijn)
- Zout en peper naar smaak
- 1 pakje slagroom
- 2 Eetlepels fijn gerneden bieslook

1. eerst de as asperges, schillen in stukken snijden en  15-20 koken.
2. dan in een pan boter smelten en hierin de fijn gesnipperde uien bakken tot ze glazig zijn.
3. meel erbij doen en goed roeren zodat er geen klonten ontstaan. dan de asperges met het water er bij doen en goed blijven roeren. Als laatste voeg de maggie blokken toe samen met zout en peper op smaak.
4. Dit doe je tot het een bepaalde dikten heeft bereikt.
5. dan het pakje slagroom, melk en de bieslook erbij doen.
6. de eieren hard koken en met een vork klein pricken en erbij doen samen met gesneden ham.

** Simple Champignon soup
[[https://www.youtube.com/watch?v=vgIplQn92gU&t=196s][Link]]\\
Ingredients:
- 4 tablespoons unsalted butter (50g)
- 2 pounds mixed mushrooms such as button, cremini, portabello, or shiitake (1kg), sliced
- Kosher salt and freshly ground black pepper
- 1 medium onion, finely chopped (about 8 ounces; 225g)
- 4 medium cloves garlic, minced
- 2 tablespoons flour (45g)
- 1 cup dry sherry or white wine (235ml)
- 1 cup milk (235ml)
- 5 cups (1.2L) homemade or store-bought low-sodium chicken stock, or water
- 2 bay leaves
- 2 sprigs fresh thyme
- Squeeze of lemon juice (optional)
- Minced fresh herbs such as parsley, chervil, tarragon, and chives for serving.
- Drizzle extra-virgin olive oil, for serving

Directions:
1) Melt butter in a large saucepan or Dutch oven over medium-high heat. Add mushrooms, season with salt and pepper, and cook, stirring frequently, until liquid has evaporated and mushrooms are well-browned, about 12 minutes total. Add onion and cook, stirring, until softened, about 3 minutes. Add garlic and cook until fragrant, about 30 seconds. Add flour and stir to combine.
2) Add sherry or wine and cook until reduced by about half, scraping up browned bits from the bottom of the pan. Add milk, chicken stock, bay leaves, and thyme sprigs and stir to combine. Bring to a bare simmer and cook for 20 minutes.
3) Using tongs, remove bay leaves and thyme. Blend soup with an immersion blender or in batches using a countertop blender. Season to taste with more salt and pepper and a squeeze of lemon juice (if desired). Serve immediately, garnished with minced herbs and olive oil.
