#+title: Flatbread

[[https://www.melskitchencafe.com/homemade-flatbread-greek-pocketless-pitas-with-a-simple-tutorial/][Link]]

Ingredients:
- 2 teaspoons instant yeast
- 1 teaspoon granulated sugar
- ⅔ cup warm water, about 100 degrees, warm but not hot to the touch
- ½ cup warm milk, about 100 degrees, warm but not hot to the touch
- 1 tablespoon extra-virgin olive oil
- 1 teaspoon salt
- 3 cups ( 426 g) bread flour, more or less (see note)

Steps
1. In a large bowl (or bowl of an electric stand mixer fitted with the dough hook), mix the yeast, sugar water, milk, oil, salt and one cup of the flour until well combined.
2. Gradually add the remaining flour until a soft dough is formed. It will pull away from the sides of the bowl to form a ball but still be slightly soft to the touch (see the note). Knead the dough for 4-5 minutes until it is soft and smooth.
3. Place the dough in a lightly greased bowl and cover with greased plastic wrap; let rise until doubled, about an hour or so.
4. Divide the dough into six or eight equal pieces. Cover with a cloth or plastic wrap and let the dough pieces rest for 10-15 minutes (this helps relax the gluten so they are easier to roll out).
5. Working with one piece at a time, on a lightly greased or floured counter, roll the dough about 1/8-inch thick into a large circle, about 7-8 inches in diameter.
6. Heat a griddle or skillet to medium heat (I preheat my electric griddle to 300 degrees). When the griddle/skillet is hot, cook the flatbread for 2-3 minutes on the first side until it bubbles and puffs. Flip it over with a pair of tongs and cook on the second side until it is golden and spotty. If the skillet isn’t hot enough, the bread can turn out dry (and won’t bend easily) from being overcooked so look for the right amount of heat that will cook the flatbread in 2-3 minutes max per side.
7. Transfer the flatbread to a plate or work surface and cover with a clean kitchen towel. Repeat with the remaining dough (I can fit two pieces of flatbread on my electric griddle so I roll out two at a time), stacking each warm flatbread on top of the others and covering with the towel.
8. The flatbread can be made, cooked, cooled and frozen with great results. It is best served the day it is made but can be reheated gently the day after, if needed.


Notes:
This will result in 6 flatbreads
