#+title: Flatbread

* Flatbread
[[https://www.recipetineats.com/easy-soft-flatbread-yeast/][Link]]

Ingredients:
- 300 g plain flour (all purpose flour) (level cups, unsifted, not packed), + keep 1/4 cup extra for dusting & adjusting dough
- 1/2 tsp salt
- 3 1/2 tbsp / 50g unsalted butter (1.75 oz)
- 185 ml milk
- 1/2 tbsp oil (for cooking)

Steps:
1) Melt butter in milk: Combine butter and milk and heat until butter is just melted – on stove or in microwave.
2) Combine Dry: Combine 2 cups flour, salt, butter and milk in a bowl.
3) Knead 2 minutes: Sprinkle work surface with flour then knead for a few minutes until it is smooth – it doesn't need much kneading. Add extra flour if the dough is too sticky.
4) Rest 30 minutes: Wrap with cling wrap and rest at room temperature for 30 minutes or so.
5) Roll into rounds: Dust bench top with flour, cut dough into 4 pieces, roll into balls, then roll out into about 1/8" / 0.3cm thick rounds.
6) Heat oil: Heat 1/2 tbsp olive oil in a non stick pan over medium heat – or lower if you have a heavy based skillet. (Note 1)
7) Cook: Place one flatbread in the pan, cook for around 1- 1 1/2 minutes – it should bubble up (see photo in post)- then flip and cook the other side, pressing down if it puffs up. There should be a smallish golden brown spots on both sides.
8) Keep wrapped in tea towel: Stack the cooked bread and keep wrapped with a tea towel – the moisture helps soften the surface, making them even more pliable. Continue to cook with remaining pieces.
9) Brush with butter or oil (optional): Brush or spray bread with olive oil or melted butter, for a more luxurious finish. Or even with melted butter mixed with minced garlic for a garlic butter version!
