#+title: General Tips

These are some general tips that about baking that can be usefull.
* Kneading the dough by hand is not needed
In recipes it will often be mentioned that they would reccomend something like a stretch and fold or other alternatives that can be used to knead the dough.
If you have a stand mixer with a dough hook like me this step is not needed since you can just use your stand mixer, as a general tip if they ask you to knead for 10 minutes by hand, a stand mixer with a dough hook can do this in 2.
* Proof dough when it's cold
This [[https://www.tasteofhome.com/article/how-to-proof-bread-when-its-cold-outside-and-inside/][website]] has some good tips on how to proof your dough even when it's cold.

1. Proofing Bread in the Oven
   To proof bread in the oven, place a glass baking dish on the bottom rack of the oven and fill it with boiling water. Stash your dough on the middle or top rack and shut the door. The steam and heat from the boiling water will create a warm and steamy environment for the dough—exactly what you want for a good rise.
