#+TITLE: Ideas
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: \n:t

* Ideas
** Focaccia Sandwich and Pizza :Bread:Pizza:Sandwich:
This [[https://www.youtube.com/watch?v=eq8vuOSnV68][video]] seemed interesting about how they make use of focaccia

** zha jiang min :Chinese:Noodles:Pork:
[[https://youtu.be/NM4ArR-qbHQ][Link]] \\
1-Hour Noodles \\
Servings: 2 \\
Ingredients 
- 2 tablespoons plus 1 teaspoon vegetable oil, divided 
- 1 tablespoon plus 1 teaspoon minced garlic, divided 
- 1 tablespoon minced fresh ginger 
- 1 tablespoon minced shallot 
- 4 ounces 80/20 ground pork 
- 1 tablespoon fermented soy bean paste 
- 1 tablespoon sweet bean sauce 
- 1 teaspoon dark soy sauce 
- ¼ cup cornstarch slurry (8 teaspoons cornstarch mixed with 4 teaspoons water) 
- 1 large egg, beaten 
- 360 grams fresh noodle of choice 
- 1 Persian cucumber, thinly sliced 
- ½ cup fresh cilantro leaves 
 
Preparation 
1. In  a medium pan, heat 1 tablespoon of vegetable oil over medium heat. Add 1  tablespoon of minced garlic, the ginger, and shallot and sauté until  lightly aromatic, 1-2 minutes. Add the ground pork to the pan and cook,  undisturbed, until golden brown, 3-5 minutes.  
2. Meanwhile,  in a small pan, heat another tablespoon of vegetable oil over  medium-low heat. Add the soy bean paste and sweet bean sauce and cook  until caramelized, 1-2 minutes, being careful not to burn. 
3. Add  the caramelized bean paste mixture to the ground pork mixture and stir  to combine. Add the soy sauce and cook for another 30 seconds to  incorporate. Add the cornstarch slurry, reduce the heat to low, and  simmer for about 15 minutes, adding a few tablespoons of water at a time  as needed to keep the mixture at a simmer. 
4. Meanwhile,  heat a small pan over low heat. Add the remaining  teaspoon of  vegetable oil, then pour in the egg and tilt the pan to spread in a thin  layer. Cook until the top is just set, then remove the egg crepe from  the pan. Let cool, then thinly slice. 
5. Cook the noodles according to the package instructions, then drain.  
6. Place  the cooked noodles in a serving bowl and top with the ground pork  mixture. Garnish with the egg crepe strips, cucumber, cilantro, and  remaining teaspoon of minced garlic. 
Enjoy! 
** Calzone :Italian:Pizza:
[[https://www.youtube.com/watch?v=PrbpuNZyoUQ][link]]
** Poblano con queso taco :Mexican:Cheese:Taco:
This [[https://youtu.be/YtkyC2Ctz6E][recipe]] looked interesting.
** Crispy Baked wings :Chicken:Wings:
This just looks [[https://www.youtube.com/watch?v=mh2AXh1eRmE][good]].
** PK Chicken Karahi :Chicken:
[[https://www.youtube.com/watch?v=4PMmH2-5wJM][link]]
