#+TITLE: Soup

* Soup
** Miso Soup :Soup:Japanese:
This [[https://minimalistbaker.com/15-minute-miso-soup-with-greens-and-tofu/][recipe]] was alright although quite fishy might need some adjustments.
** Asperge Soup :Soup:
Voor 5l asperges soep
ingredienten:
- 250 boter
- 3 dikke uien
- 6 grote eetlepels meel en een ½ liter melk
- 5 maggie blokken
- 4 eieren
- 3kg asperges (mag stukken zijn)
- Zout en peper naar smaak
- 1 pakje slagroom
- 2 Eetlepels fijn gerneden bieslook

1. eerst de as asperges, schillen in stukken snijden en  15-20 koken.
2. dan in een pan boter smelten en hierin de fijn gesnipperde uien bakken tot ze glazig zijn.
3. meel erbij doen en goed roeren zodat er geen klonten ontstaan. dan de asperges met het water er bij doen en goed blijven roeren. Als laatste voeg de maggie blokken toe samen met zout en peper op smaak.
4. Dit doe je tot het een bepaalde dikten heeft bereikt.
5. dan het pakje slagroom, melk en de bieslook erbij doen.
6. de eieren hard koken en met een vork klein pricken en erbij doen samen met gesneden ham.
