#+title: Black Pepper Beef
#+OPTIONS: \n:t

* Black pepper beef :Beef:Wok:
[[https://schoolofwok.co.uk/tips-and-recipes/black-pepper-beef][Link]]\\
Ingredients:
- 350g steak, sliced into strips against the grain
- 1 onion, julienned
- 1/2 red pepper, julienned
- 1 spring onion
- 1/4 of a thumb size piece of ginger

THE MARINADE
- 1 teaspoon cornflour (cornstarch)
- 1 teaspoon light soy sauce
- 1 teaspoon pure sesame oil

THE SAUCE
- 1/4 teaspoon salt
- 1/2 teaspoon sugar
- 1/2 teaspoon crushed black pepper
- 1 tablespoon Lee Kum Kee black pepper sauce
- 50 ml chicken stock
- 1 tablespoon light soy sauce
- 1 tablespoon oyster sauce
- 2 teaspoons Shaoxing rice wine

Preparation:
1) Remove any rind or fat from the steak, then slice thinly. Tenderize by bashing them with a cleaver or meat hammer, creating a large surface area for quick cooking.
2) Mix all the marinade ingredients with the meat. Massage the marinade into the meat, marinade for 30 minutes, or overnight for more flavor.
3) Mix the sauce ingredients together in a small bowl.
Cooking:
1) Heat 2 tablespoons vegetable oil in a wok to high heat. Sear your meat for a couple of minutes on each side and set aside.
2) Add oil to the wok and when smoking hot, add the ginger and spring onions, once they have slightly softened, add the pepper and onions.
3) Maintaining the high heat, pour in your sauce, return the meat to the wok and continue to stir-fry for an additional 30 seconds.
4) Serve and enjoy.
