#+title: Chicken Enchiladas
#+OPTIONS: \n:t

* Chicken Enchiladas :Chicken:Mexican:
Ingredients:
- 600 - 700 gram chicken
- 1 onion, chopped
- 1 cup shredded cheese
- 1 tablespoon dried parsley
- 1/2 teaspoon dried oregano
- 1/2 teaspoon ground black pepper
- 1/2 teaspoon salt (Optional)
- 1 (15 ounce) can tomato sauce
- 1/2 cup water
- 1 tablespoon chili powder
- 1 clove garlic, minced
- 8 (10 inch) flour tortillas
- 1 (12 ounce) jar taco sauce
- 3/4 cup shredded cheese

Ingredients Dip Sauce:
- creme fraiche
- 1 teaspoon kurkuma
- 1 teaspoon dille
- 1 teaspoon bieslook
- 1 teaspoon peterselie
- 2 teaspoon uitenpoeder
- 1 teaspoon peper
- 1 teaspoon zout

Notes:
- Maybe watch out with the chili powder on this one.

Steps:
1) Preheat oven to 350 degrees F (175 degrees C).
2) In a medium, non-stick skillet over medium heat, cook chicken until no longer pink and juices run clear. Drain excess fat. Cube the chicken and return it to the skillet. Add the onion, sour cream, Cheddar cheese, parsley, oregano and ground black pepper. Heat until cheese melts. Stir in salt, tomato sauce, water, chili powder, and garlic.
3) Roll even amounts of the mixture in the tortillas. Arrange in a 9x13 inch baking dish. Cover with taco sauce and 3/4 cup Cheddar cheese. Bake uncovered in the preheated oven 20 minutes. Cool 10 minutes before serving.

Dip sauce:
1) Meng in een schaaltje de crème fraîche met de kurkuma, dille, bieslook, peterselie, 2 theelepels uienpoeder, peper en zout allemaal 1 theelepel voor een heerlijk dipsausje.
