#+title: Easy Mexican Casserole
#+OPTIONS: \n:t

* Easy Mexican Casserole :Mexican:Beef:
[[https://www.allrecipes.com/recipe/20680/easy-mexican-casserole/][Link]]\\
Ingredients: 
- 1 pound lean ground beef 
- 2 cups salsa 
- 1 (16 ounce) can chili beans, drained 
- 3 cups tortilla chips, crushed 
- 2 cups sour cream 
- 1 (2 ounce) can sliced black olives, drained 
- 1/2 cup chopped green onion 
- 1/2 cup chopped fresh tomato 
- 2 cups shredded Cheddar cheese 
 
Steps:
1) Preheat oven to 350 degrees F (175 degrees C). 
2) In  a large skillet over medium-high heat, cook ground beef until no longer  pink. Stir in salsa, reduce heat, and simmer 20 minutes, or until  liquid is absorbed. Stir in beans, and heat through. 
3) Spray  a 9x13 baking dish with cooking spray. Spread crushed tortilla chips in  dish, and then spoon beef mixture over chips. Spread sour cream over  beef, and sprinkle olives, green onion, and tomato over the sour cream.  Top with Cheddar cheese. 
4) Bake in preheated oven for 30 minutes, or until hot and bubbly. 
