#+title: Yogurt Marinated Chicken Thighs

[[https://diethood.com/yogurt-marinated-chicken-thighs/][Link]]

Ingredients:
- 1 cup nonfat plain yogurt
- 1 tablespoon extra virgin olive oil
- 1 tablespoon curry powder
- 1 tablespoon chili powder
- 1/2 tablespoon cumin
- 1 teaspoon garlic powder
- 1 teaspoon onion powder
- 1 teaspoon salt
- 8 (about 2 pounds, total) boneless, skinless chicken thighs

Steps
1. In a large mixing bowl, combine yogurt, oil, curry powder, chili powder, cumin, garlic powder, onion powder, and salt; mix to combine.
2. Add chicken thighs and toss until well-coated.
3. Cover and marinate for at least 30 minutes. You can also cover and refrigerate for up to 8 hours.
4. Remove chicken from fridge and let stand for 15 minutes at room temperature.

Oven Method:
1. Set oven to BROIL.
2. Transfer chicken to a broiler pan or foil-lined baking sheet or broiler pan. Discard yogurt marinade.
3. Broil chicken for 8 minutes; flip chicken thighs and broil 7 to 8 minutes more, or until internal temperature reaches 165°F.
4. Remove from oven.

Grill Method:
1. Preheat grill to medium-high, about 425°F to 450°F.
2. Brush the grill grates with oil.
3. Place chicken thighs on grill and grill for 7 minutes per side, or until internal temperature of chicken reaches 165˚F.
